package com.coderli.yami.ui;

import javax.swing.*;
import java.awt.*;

/**
 * @author li.hzh
 * @date 16/2/19
 */
public class MainBoard {
    private JList list1;
    private JPanel panel1;

    MainBoard() {
    }

    public JList getList1() {
        return list1;
    }

    public void setList1(JList list1) {
        this.list1 = list1;
    }

    public JPanel getPanel1() {
        return panel1;
    }

    public void setPanel1(JPanel panel1) {
        this.panel1 = panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-3589830)), null));
        list1 = new JList();
        panel1.add(list1, BorderLayout.WEST);
        final JLabel label1 = new JLabel();
        label1.setEnabled(false);
        label1.setText("文章列表");
        label1.putClientProperty("html.disable", Boolean.FALSE);
        panel1.add(label1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
